# Generated by Django 4.0.4 on 2022-05-21 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraise', '0003_alter_charity_user'),
        ('donate', '0002_donation_donationmessage_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='fundraise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundraise.charity'),
        ),
    ]
