# Generated by Django 4.0.4 on 2022-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='Charity'),
            preserve_default=False,
        ),
    ]
