# Generated by Django 4.0.1 on 2022-05-19 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('address', models.CharField(max_length=30, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, default='', null=True, upload_to='user_profile_pic')),
                ('User', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
